stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - assets/original_data/train.csv
    - src/preprocess.py
    outs:
    - assets/preprocessed/
  featurize:
    cmd: python src/featurize.py
    deps:
    - assets/preprocessed/test.csv
    - assets/preprocessed/train.csv
    - src/preprocess.py
    outs:
    - assets/featurized/
  train_test_eval:
    cmd: python src/model.py
    deps:
    - assets/featurized
    - src/model.py
    outs:
    - assets/models
    metrics:
    - assets/eval/scores.json:
        cache: false
